"""Add missing updated_at column to categories and menu_items tables

Revision ID: 5991550abd23
Revises: 1c9ea10a76e2
Create Date: 2025-08-28 00:02:27.210562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5991550abd23'
down_revision: Union[str, Sequence[str], None] = '1c9ea10a76e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default to handle existing data
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('menu_items', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'updated_at')
    op.drop_column('categories', 'updated_at')
    # ### end Alembic commands ###