"""Fix model relationships and add missing back_populates

Revision ID: 74133ef50b5f
Revises: a8ff746d995f
Create Date: 2025-08-27 12:33:33.603104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74133ef50b5f'
down_revision: Union[str, Sequence[str], None] = 'a8ff746d995f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###