"""add_translation_fields_to_categories_menu_items_modification_types

Revision ID: 99c17b785c50
Revises: ce5e11f5e637
Create Date: 2025-08-28 07:35:12.110922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c17b785c50'
down_revision: Union[str, Sequence[str], None] = 'ce5e11f5e637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_translations', sa.JSON(), nullable=True))
    op.add_column('menu_items', sa.Column('name_translations', sa.JSON(), nullable=True))
    op.add_column('menu_items', sa.Column('description_translations', sa.JSON(), nullable=True))
    op.add_column('modification_types', sa.Column('name_translations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modification_types', 'name_translations')
    op.drop_column('menu_items', 'description_translations')
    op.drop_column('menu_items', 'name_translations')
    op.drop_column('categories', 'name_translations')
    # ### end Alembic commands ###